// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeSpendDashboard.Models.Entity;

namespace TradeSpendDashboard.Migrations
{
    [DbContext(typeof(TradeSpendDashboardContext))]
    [Migration("20220617161449_UpdateInitialTradeSpendDashboard")]
    partial class UpdateInitialTradeSpendDashboard
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterCustomerLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerLevel1")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterCustomerLevel");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterCustomerMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerMap")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("NewChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("OldChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterCustomerMap");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Icon")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("IdParent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("MasterMenu");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterMenuRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Create")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Update")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterMenuRole");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterRole");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterRoleBudgetOwner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BudgetOwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MasterRoleBudgetOwner");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterUsers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("MasterUsers");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterUsersRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("MasterUsersRole");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Master.MasterUsersSpending", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BudgetOwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfitCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("MasterUsersSpending");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterBudgetOwner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BudgetOwner")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterBudgetOwner");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterBudgetOwnerMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BudgetOwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ValueTradeSpend")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.ToTable("MasterBudgetOwnerMap");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("ProfitCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterCategory");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterCategoryMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterCategoryMap");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterChannel");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterGL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("GLCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterGL");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterGLType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterGLType");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.MasterProfitCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProfitCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("MasterProfitCenter");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Temp.HistorycalContract", b =>
                {
                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("BudgetDir_Disc_excPPn")
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("BudgetQuar_Rwrd_ExcPPn")
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("CR")
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("Direct_Discount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Distributor_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nama_BAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Oulet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Outlet_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parent_SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price_AfterTax")
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("Price_BeforeTax")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("QtyMonth")
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("Quarter_reward")
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("SalesPerMonth")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.ToTable("HistorycalContract");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Temp.TempGuideline", b =>
                {
                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GuidlineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SubChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.ToTable("TempGuideline");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.Temp.TempSalesProjection", b =>
                {
                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GrossSales")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Outlet")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SalesProjectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SubChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.ToTable("TempSalesProjection");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Actual.TradeHeadPrimarySalesActual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadPrimarySalesActual");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Actual.TradeHeadSecondarySalesActual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadSecondarySalesActual");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Actual.TradeHeadSpendingActual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadSpendingActual");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Update.TradeHeadPrimarySalesUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadPrimarySalesUpdate");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Update.TradeHeadSecondarySalesUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadSecondarySalesUpdate");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Update.TradeHeadSpendingUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadSpendingUpdate");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Upload.TradeHeadPrimarySalesOutlook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadPrimarySalesOutlook");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Upload.TradeHeadSecondarySalesOutlook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadSecondarySalesOutlook");
                });

            modelBuilder.Entity("TradeSpendDashboard.Models.Entity.TradeSpendDashboard.Transaction.Upload.TradeHeadSpendingOutlook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.HasKey("Id");

                    b.ToTable("TradeHeadSpendingOutlook");
                });
#pragma warning restore 612, 618
        }
    }
}
